apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel_templete
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laravel_templete
  template:
    metadata:
      labels:
        app: laravel_templete
    spec:
      containers:
        - name: laravel_templete-container
          image: your-docker-image:tag
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: laravel_templete-service
spec:
  selector:
    app: laravel_templete
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
